Improve the check_binary() and check_compiler() functions

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -114,9 +114,9 @@ check_binary() {
    id=$1
    shift
 
-   for path in $*
+   for x in $*
    do
-       test -f $path
+       path=`which $x 2>/dev/null`
        if [ $? = 0 ] ; then
            eval "$id=\"$path\""
            return
@@ -198,10 +198,14 @@ check_target() {
 
 check_compiler() {
     printf "checking for a C compiler.. "
-    check_binary default_cc "/usr/bin/cc" "/usr/bin/gcc" "/usr/sfw/bin/gcc" "`which gcc 2>/dev/null`"
-    finalize cc "$default_cc"
-    test -x "$cc" || err "Unable to locate a C compiler"
-    echo "$cc"
+    if [ "$cc" = "" ] ; then
+        check_binary default_cc "$cc" cc gcc clang
+        finalize cc "$default_cc"
+        test -x "$cc" || err "Unable to locate a C compiler"
+        echo "$cc"
+    else
+        echo "$cc (set by the CC environment variable)"
+    fi
 }
 
 check_linker() {
