Initial efforts at fixing "make package"

diff --git a/testing/simple/configure b/testing/simple/configure
--- a/testing/simple/configure
+++ b/testing/simple/configure
@@ -1,5 +1,44 @@
 #!/bin/sh
+#
+# Bootstrap configuration script for Makeconf
+#
+# Author:   Mark Heily <mark@heily.com>
+#
 
-export CFLAGS
+die() {
+  printf "\n*** ERROR: $1 ***\n\n$2\n\n"
+  exit 1
+}
 
-RUBYLIB=../../lib ../../bin/configure.sh $*
+if [ "$RUBY" != "" ] ; then
+  ruby=$RUBY
+else
+  ruby=`which ruby`
+fi
+
+printf 'checking for ruby.. '
+if [ ! -x "$ruby" ] ; then
+  echo 'no'
+  die 'Ruby was not found' 'Please install Ruby from http://www.ruby-lang.org/'
+fi
+
+# For this test only..
+RUBYLIB="./makeconf"
+
+if [ "$RUBYLIB" != "" ] ; then
+  echo "$ruby (RUBYLIB=$RUBYLIB)"  
+  export RUBYLIB
+else
+  echo $ruby
+fi
+
+
+printf 'checking for makeconf.. '
+ruby -e "require 'makeconf'" > /dev/null 2>&1
+if [ $? -ne 0 ] ; then
+  echo 'no'
+  die 'Makeconf was not found' 'Please install Makeconf from https://rubygems.org/'
+fi
+echo 'yes'
+
+exec $ruby ./configure.rb $*
